services:
  - type: web
    name: my-express-app
    env: node
    buildCommand: |
      apt-get update && \
      apt-get install -y chromium-browser && \
      npm install
    startCommand: npm start
    envVars:
      - key: CHROME_PATH
        value: /usr/bin/chromium-browser
